# Generated by Django 4.2.16 on 2025-12-03 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=100, verbose_name='Название компании')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.CreateModel(
            name='MarketplaceCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace', models.CharField(choices=[('ozon', 'Ozon'), ('wb', 'Wildberries'), ('ym', 'Yandex Market')], max_length=10, verbose_name='Маркетплейс')),
                ('client_id', django_cryptography.fields.encrypt(models.CharField(blank=True, help_text='Требуется для Ozon', max_length=255, verbose_name='Client ID'))),
                ('api_key', django_cryptography.fields.encrypt(models.CharField(max_length=255, verbose_name='API Key'))),
                ('api_secret', django_cryptography.fields.encrypt(models.CharField(blank=True, help_text='Для WB и Яндекс.Маркет', max_length=255, verbose_name='API Secret'))),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Учётные данные маркетплейса',
                'verbose_name_plural': 'Учётные данные маркетплейсов',
                'unique_together': {('user', 'marketplace')},
            },
        ),
    ]
