# Generated by Django 4.2.16 on 2026-05-28 12:44

from django.conf import settings
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEmailPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активировать email-уведомления')),
                ('notify_integration_errors', models.BooleanField(default=True, verbose_name='Ошибки интеграций')),
                ('notify_moderation_queue', models.BooleanField(default=True, verbose_name='Новые ответы на модерации')),
                ('moderation_digest_interval', models.CharField(choices=[('immediate', 'Мгновенно'), ('hourly', 'Раз в час'), ('daily', 'Раз в сутки')], default='hourly', max_length=20, verbose_name='Частота дайджеста модерации')),
                ('notify_processing_report', models.BooleanField(default=True, verbose_name='Отчёты обработки отзывов')),
                ('notify_security', models.BooleanField(default=True, verbose_name='Безопасность аккаунта')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_prefs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Настройки email-уведомлений',
                'verbose_name_plural': 'Настройки email-уведомлений',
            },
        ),
        migrations.CreateModel(
            name='UserModuleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(help_text="Имя модуля (например, 'ai_reviews')", max_length=100)),
                ('config_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Конфигурация в формате JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Конфигурация модуля',
                'verbose_name_plural': 'Конфигурации модулей',
                'indexes': [models.Index(fields=['user', 'module_name'], name='accounts_us_user_id_e5f790_idx')],
                'unique_together': {('user', 'module_name')},
            },
        ),
    ]
