# Generated by Django 4.2.16 on 2025-12-16 18:32

from django.conf import settings
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OzonReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_id', models.BigIntegerField(db_index=True, verbose_name='ID отзыва в Ozon')),
                ('product_id', models.BigIntegerField(verbose_name='ID товара в Ozon')),
                ('offer_id', models.CharField(blank=True, max_length=200, verbose_name='Offer ID')),
                ('sku', models.CharField(blank=True, max_length=100, verbose_name='SKU')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('rating', models.PositiveSmallIntegerField(null=True, verbose_name='Оценка')),
                ('created_at', models.DateTimeField(verbose_name='Дата создания отзыва в Ozon')),
                ('product_name', models.CharField(blank=True, max_length=500, verbose_name='Название товара')),
                ('product_characteristics', models.JSONField(blank=True, default=dict, verbose_name='Характеристики товара')),
                ('has_answer', models.BooleanField(default=False, verbose_name='Есть ответ?')),
                ('answer_text', models.TextField(blank=True, verbose_name='Текст ответа')),
                ('answer_posted_at', models.DateTimeField(blank=True, null=True, verbose_name='Ответ отправлен')),
                ('answer_ozon_id', models.CharField(blank=True, max_length=100, verbose_name='ID комментария в Ozon')),
                ('moderation_status', models.CharField(choices=[('not_submitted', 'Не отправлено'), ('pending', 'На модерации'), ('sent', 'Отправлено')], db_index=True, default='not_submitted', max_length=20, verbose_name='Статус модерации')),
                ('created_local', models.DateTimeField(auto_now_add=True)),
                ('updated_local', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ozon_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Ozon отзыв',
                'verbose_name_plural': 'Ozon отзывы',
            },
        ),
        migrations.CreateModel(
            name='ReviewAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='Данные анализа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('tokens_used', models.IntegerField(default=0, verbose_name='Использовано токенов')),
                ('model_version', models.CharField(default='unknown', max_length=100, verbose_name='Версия модели')),
                ('is_success', models.BooleanField(default=True, verbose_name='Успешный анализ')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Сообщение об ошибке')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='ai_reviews.ozonreview', verbose_name='Отзыв')),
            ],
            options={
                'verbose_name': 'Анализ отзыва',
                'verbose_name_plural': 'Анализы отзывов',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_success', 'created_at'], name='ai_reviews__is_succ_a9f956_idx'), models.Index(fields=['review'], name='ai_reviews__review__c18636_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='ozonreview',
            index=models.Index(fields=['user', 'has_answer', 'created_at'], name='ai_reviews__user_id_ac93e9_idx'),
        ),
        migrations.AddIndex(
            model_name='ozonreview',
            index=models.Index(fields=['moderation_status'], name='ai_reviews__moderat_50ad40_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ozonreview',
            unique_together={('user', 'review_id')},
        ),
    ]
