# Generated by Django 4.2.16 on 2025-12-03 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField(verbose_name='Текст отзыва')),
                ('product_model', models.CharField(blank=True, max_length=255, null=True, verbose_name='Модель товара')),
                ('original_rating', models.IntegerField(blank=True, null=True, verbose_name='Исходная оценка')),
                ('analysis_data_json', models.TextField(blank=True, default='{}', verbose_name='Данные анализа (JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('tokens_used', models.IntegerField(default=0, verbose_name='Использовано токенов')),
                ('model_version', models.CharField(default='unknown', max_length=100, verbose_name='Версия модели')),
                ('is_success', models.BooleanField(default=True, verbose_name='Успешный анализ')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Сообщение об ошибке')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_analyses', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Анализ отзыва',
                'verbose_name_plural': 'Анализы отзывов',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='ai_reviews__user_id_824bfe_idx'), models.Index(fields=['is_success', 'created_at'], name='ai_reviews__is_succ_a9f956_idx')],
            },
        ),
    ]
