# Generated by Django 4.2.16 on 2026-05-13 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewanalysis',
            name='review',
            field=models.ForeignKey(blank=True, help_text='Оставьте пустым для аналитики дашборда (общий отчет)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='ai_reviews.ozonreview', verbose_name='Отзыв'),
        ),
    ]
