# Generated by Django 4.2.16 on 2026-05-13 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_reviews', '0002_alter_reviewanalysis_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewanalysis',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Оставьте пустым для аналитики отзыва (конкретный отчет)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
