# Generated by Django 4.2.16 on 2026-05-26 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_reviews', '0003_reviewanalysis_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ozonreview',
            name='product_info',
            field=models.JSONField(blank=True, default=dict, verbose_name='Полная информация о товаре'),
        ),
    ]
